### ISSUE TITLE
Compatibility Symfony flash bag and Drupal messages.

### ISSUE THREAD

**Issue by pokap** [ekino/EkinoDrupalBundle#33]
In Drupal core (core/includes/bootstrap.inc) there is 2 functions for the same functionality of FlashBag sessions, **drupal_set_message** and **drupal_get_messages**.

The only difference is the storage name, in Symfony2 __sf2_flashes_ and in Drupal _messages_.

https://github.com/ekino/EkinoDrupalBundle/blob/master/Port/DrupalFlashBag.php#L33

Do you think it is more interesting to have the same name for improve compatibility ?

**Comment by rande** [comment]
;)
