### ISSUE TITLE
White screen of death on login

### ISSUE THREAD

**Issue by zenmedia** [ekino/EkinoDrupalBundle#40]
When logging in to drupal i am getting a white screen of death, which when following through the debugging it highlighting that DrupalRequestListener onKernelRequest is stopping event propagation.

I have got this down to the buildResponse call (https://github.com/ekino/EkinoDrupalBundle/blob/master/Drupal/DrupalRequestListener.php#L64).

Unfortunately i don't know the inner workings of symfony as much as i would like and i am "stuck". When the page is refreshed drupal loads successfully in a logged in state, but symfony doesn't authenticate.

Look forward to your assistance.

Version information:
Drupal 7.43
Symfony 2.3.41
Drush 6
FOS User Bundle 1.3

**Comment by rande** [comment]
Try to rethrow the exeception here: https://github.com/ekino/EkinoDrupalBundle/blob/master/Drupal/Drupal.php#L507

**Comment by zenmedia** [comment]
Sorry for the delay, there is no errors being generated by the call_user_func_array method, but you are correct this is where is it falling down.
