### ISSUE TITLE
Using EkinoDrupalBundle to only access Drupal contents from Symfony code

### ISSUE THREAD

**Issue by elvismdev** [ekino/EkinoDrupalBundle#44]
Hi @eko,

My intention here is to use this bundle from a stand alone Symfony app, only to access the contents from a Drupal site and migrate data to a WordPress site. For the WordPress workload I'm looking forward to use https://github.com/ekino/EkinoWordpressBundle at the same time.

For this goal (ONLY access to Drupal data from Symfony) I have my doubt's if I will need to do exactly all the steps described in the [README](https://github.com/ekino/EkinoDrupalBundle/blob/master/README.md) in order to have it working properly without issues.

Could I skip some parts I don't need? Or even better, could you briefly explain what's the only setup I will need to perform to make my Symfony app capable to fetch the contents I need from the Drupal site?

Thanks!

**Comment by eko** [comment]
Hi @elvismdev,

I think that the main thing to do in your case is to use the `background` strategy as you won't need to render Drupal at any time: you just need your Symfony application to access it.

```yaml
ekino_drupal:
    strategy_id: ekino.drupal.delivery_strategy.background
```

You do not need optional config parameters too like `session` or `security`.

You also don't need to update the Symfony's `index.php` unless you want the Symfony container to be available into Drupal as a global variable.

You also don't need to update your Symfony's `app/config/security.yml` file as you don't have to manage security between Symfony and Drupal in your case.

I hope I could help you a little bit to understand the bundle's configuration.

**Comment by elvismdev** [comment]
Thanks @eko! This info really helps me more to understand the pieces I only need for my particular case. I will try putting everything together soon and let you know if I run into issues.
